# -*- coding: utf-8 -*-
"""CreateException1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WWfedqv_Yxb_6teafGulk_94hLhbw57f
"""

while True:
  try:
    x = int(input("Please enter a number: "))
    break
  except ValueError:
    print("Invalid number... Please try again.")
  else:
    print("Unknown Error occured.")